version: '3.4'

services:
  shopping-db:
    image: europe-north1-docker.pkg.dev/cjgrp-379511/image-repo/db:latest
    hostname: shopping-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
    - "5432:5432"
    # use below build context for a local build instead of the above image
    #build:
    #  context: .

  shopping-app:
    labels:
      kompose.service.type: LoadBalancer
    image: europe-north1-docker.pkg.dev/cjgrp-379511/image-repo/app:latest
    # use below build context for a local build instead of the above image
    #build:
      #context: ./shopping-list
    hostname: shopping-app
    ports:
    - "8080:80"
    environment:
      DBHOST: shopping-db
      DBUSER: postgres
      DBPASSWORD: password
      DBNAME: postgres
      DBPORT: 5432
