apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: shopping-db
  name: shopping-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: shopping-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: shopping-db
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_USER
              value: postgres
          image: europe-north1-docker.pkg.dev/cjgrp-379511/image-repo/db:latest
          name: shopping-db
          ports:
            - containerPort: 5432
          resources: {}
      hostname: shopping-db
      restartPolicy: Always
status: {}
